version: "3.7"
services:
  # The Penumbra daemon
  pd-node0:
    container_name: penumbra-node0
    build:
      context: .
    environment:
      - RUST_LOG=${RUST_LOG:-warn,pd=info,penumbra=info}
    volumes:
      - ~/scratch/testnet_build/node0/pd:/pd
    command: pd start --host 0.0.0.0 --database-uri postgres://postgres:postgres@db-node0/penumbra -r /pd/rocksdb
    restart: on-failure
    networks:
      localnet:
        ipv4_address: 192.167.10.10
    ports:
      - "26658:26658"
      - "26666:26666"
      - "26667:26667"

  # The Tendermint node
  tendermint-node0:
    image: "tendermint/tendermint:v0.35.0"
    container_name: tendermint-node0
    ports:
      - "26656:26656"
      - "26657:26657"
    volumes:
      - ~/scratch/testnet_build/node0/tendermint:/tendermint
    command: start --proxy-app=tcp://pd-node0:26658
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    depends_on:
      - pd-node0
    networks:
      localnet:
        ipv4_address: 192.167.10.11

  # The Penumbra daemon
  pd-node1:
    container_name: penumbra-node1
    build:
      context: .
    environment:
      - RUST_LOG=${RUST_LOG:-warn,pd=info,penumbra=info}
    command: pd start --host 0.0.0.0 --database-uri
      postgres://postgres:postgres@db-node1/penumbra -r /pd/rocksdb
    restart: on-failure
    networks:
      localnet:
        ipv4_address: 192.167.10.20
    ports:
      - "27658:26658"
      - "27666:26666"
      - "27667:26667"

  # The Tendermint node
  tendermint-node1:
    image: "tendermint/tendermint:v0.35.0"
    container_name: tendermint-node1
    ports:
      - "27656:26656"
      - "27657:26657"
    volumes:
      - ~/scratch/testnet_build/node1:/tendermint
    command: start --proxy-app=tcp://pd-node1:26658
    environment:
      - ID=1
      - LOG=${LOG:-tendermint.log}
    depends_on:
      - pd-node1
    networks:
      localnet:
        ipv4_address: 192.167.10.21

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16
