version: "3.7"
services:
  # The Penumbra daemon
  pd:
    container_name: penumbra
    build:
      context: .
    environment:
      - RUST_LOG=${RUST_LOG:-warn,pd=info,penumbra=info}
    command: pd start --host 0.0.0.0 --database-uri
      postgres://postgres:postgres@db/penumbra
    restart: on-failure
    depends_on:
      - db
    links:
      - db:db
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  # database - postgres
  db:
    image: postgres:14.0
    container_name: db
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=penumbra
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      localnet:
        ipv4_address: 192.167.10.12

  # The Tendermint node
  tendermint:
    container_name: tendermint
    image: "tendermint/tendermint"
    ports:
      - "26656-26657:26656-26657"
      - "6060:6060"
      - "27000:26660"
    volumes:
      - "tendermint_data:/tendermint"
    command: start --proxy-app=tcp://pd:26658
    depends_on:
      - pd
    networks:
      localnet:
        ipv4_address: 192.167.10.2
    build:
      context: ./tendermint/

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16

volumes:
  tendermint_data: {}
  db_data: {}
