[package]
name = "tct-spec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penumbra-tct = { path = "../tct", features = ["internal"] }
hash_hasher = "2"