[package]
name = "penumbra-storage"
version = "0.63.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
migration = []
default = ["metrics"]
rpc = ["dep:tonic", "dep:prost", "dep:serde", "dep:pbjson"]

[dependencies]
jmt = "0.9"
tokio = { version = "1.21.1", features = ["full", "tracing"] }
tokio-stream = { version = "0.1.11" }
tempfile = "3.3.0"
anyhow = "1"
async-trait = "0.1.52"
tracing = "0.1"
rocksdb = "0.21.0"
futures = "0.3"
hex = "0.4"
metrics = { version = "0.19.0", optional = true }
parking_lot = "0.12"
pin-project = "1.0.12"
smallvec = { version = "1.10", features = ["union", "const_generics"] }

# Tendermint/IBC crates 
ics23 = "0.11.0"
tendermint = { version = "0.34.0", default-features = false }
borsh = "0.10.3"
sha2 = "0.10.6"

# Used for RPC.
tonic = { version = "0.10", optional = true }
prost = { version = "0.11", optional = true }
serde = { version = "1", optional = true }
pbjson = { version = "0.5", optional = true }
ibc-proto = { version = "0.37.0", default-features = false, optional = true }

[dev-dependencies]
tempfile = "3.3.0"
tracing-subscriber = "0.3"
tokio = "1.21.1"
