[package]
name = "penumbra-ibc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
penumbra-crypto = { path = "../crypto" }
penumbra-proto = { path = "../proto" } 
tendermint = { git = "https://github.com/penumbra-zone/tendermint-rs.git", branch = "master" }

# External dependencies
#ibc-proto = { path = "../../ibc-rs/proto" }
ibc-proto = "0.17.0"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
async-trait = "0.1.52"
