[package]
name = "penumbra-funding"
version = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium-component",
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-community-pool/component",
    "penumbra-distributions/component",
    "penumbra-sct/component",
    "penumbra-shielded-pool/component",
    "penumbra-stake/component",
    "metrics",
    "futures"
]
default = ["component"]
docsrs = []

[dependencies]
anyhow = {workspace = true}
async-trait = {workspace = true}
cnidarium = {workspace = true, optional = true, default-features = true}
cnidarium-component = {workspace = true, optional = true, default-features = true}
futures = {workspace = true, optional = true}
metrics = {workspace = true, optional = true}
penumbra-asset = {workspace = true, default-features = true}
penumbra-community-pool = {workspace = true, default-features = false}
penumbra-distributions = {workspace = true, default-features = false}
penumbra-proto = {workspace = true, default-features = false}
penumbra-sct = {workspace = true, default-features = false}
penumbra-shielded-pool = {workspace = true, default-features = false}
penumbra-stake = {workspace = true, default-features = false}
serde = {workspace = true, features = ["derive"]}
tendermint = {workspace = true}
tracing = {workspace = true}

[dev-dependencies]
