apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: testnet-ingress-frontend-config
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testnet-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: testnet-ingress-ip
    networking.gke.io/managed-certificates: testnet-ingress-cert
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: testnet-ingress-frontend-config
spec:
  rules:
    # - host: rpc.testnet.penumbra.strange.love
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: testnet
    #             port:
    #               number: 26657
    - host: grpc.testnet.penumbra.strange.love
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testnet
                port:
                  number: 8080
