[package]
name = "penumbra-ibc"
version = {workspace = true}
edition = {workspace = true}

[features]
component = [
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-sct/component",
]
default = ["component", "std"]
std = ["ibc-types/std"]
docsrs = []
rpc = ["dep:tonic", "ibc-proto/client", "ibc-proto/server"]

[dependencies]
anyhow = {workspace = true}
ark-ff = {workspace = true, default-features = false}
async-trait = {workspace = true}
base64 = {workspace = true}
blake2b_simd = {workspace = true}
cnidarium = {workspace = true, optional = true, default-features = true}
hex = {workspace = true}
ibc-proto = {workspace = true, default-features = false}
ibc-types = {workspace = true, default-features = false}
ics23 = {workspace = true}
metrics = {workspace = true}
num-traits = {workspace = true, default-features = false}
once_cell = {workspace = true}
pbjson-types = {workspace = true}
penumbra-asset = {workspace = true, default-features = false}
penumbra-num = {workspace = true, default-features = false}
penumbra-proto = {workspace = true, default-features = false}
penumbra-sct = {workspace = true, default-features = false}
penumbra-txhash = {workspace = true, default-features = false}
prost = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
sha2 = {workspace = true}
tendermint = {workspace = true}
tendermint-light-client-verifier = {workspace = true}
tonic = {workspace = true, optional = true}
tower = {workspace = true}
tracing = {workspace = true}

[dev-dependencies]
tokio = {workspace = true, features = ["full"]}
