[package]
# A vendored copy of the unpublished `tracing-tower` crate.
name = "penumbra-tower-trace"
version = "0.54.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Penumbra dependencies

# External dependencies
futures = "0.3"
hex = "0.4"
http = "0.2"
pin-project = "1"
pin-project-lite = "0.2.9"
sha2 = "0.9"
tendermint = "0.32.0"
tendermint-proto = "0.32.0"
tokio = { version = "1.22", features = ["full"] }
tokio-stream = "0.1"
tokio-util = "0.7"
tonic = "0.8.1"
tower = { version = "0.4", features = ["full"] }
tower-service = "0.3.2"
tracing = "0.1"
