[book]
authors = ["Penumbra Team"]
language = "en"
multilingual = false
src = "src"
title = "The Penumbra Guide"

[preprocessor.katex]
renderers = ["html"]

[output.katex]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
curly-quotes = true
fold = { enable = true, level = 1 }
git-repository-url = "https://github.com/penumbra-zone/penumbra"
additional-js =["theme/js/mermaid.min.js", "theme/js/mermaid-init.js"]


