[package]
name = "penumbra-tendermint-proxy"
version = "0.51.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Penumbra dependencies
penumbra-proto = { path = "../proto", features = ["rpc"] }
penumbra-transaction = { path = "../transaction" }

# External dependencies
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
futures = "0.3"
hex = "0.4"
http = "0.2"
metrics = "0.19.0"
pbjson-types = "0.5"
pin-project = "1"
pin-project-lite = "0.2.9"
sha2 = "0.9"
tendermint = "0.29.0"
tendermint-config = "0.29.0"
tendermint-proto = "0.29.0"
tendermint-light-client-verifier = "0.29.0"
tendermint-rpc = { version = "0.29.0", features = ["http-client"] }
tokio = { version = "1.22", features = ["full"] }
tokio-stream = "0.1"
tokio-util = "0.7"
tonic = "0.8.1"
tower = { version = "0.4", features = ["full"] }
tower-service = "0.3.2"
tracing = "0.1"
url = "2"
