[package]
name = "cnidarium-component"
version = "0.64.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cnidarium = { path = "../cnidarium", default-features = false }
async-trait = "0.1.52"
anyhow = "1"
tendermint = "0.34.0"
hex = "0.4"
