---
# Values file for "testnet-preview.penumbra.zone" CI deploys.
# Mostly sets the FQDNs on the ingress.
ingress:
  enabled: true
  hosts:
    # The Tendermint RPC port.
    rpc: rpc.testnet-preview.penumbra.zone
    # The pd gRPC port.
    grpc: grpc.testnet-preview.penumbra.zone
    # The Grafana HTTP web interface, for viewing dashboards.
    grafana: grafana.testnet-preview.penumbra.zone
