[package]
name = "penumbra-wasm"
version = "0.51.0"
authors = ["Valentine <valentine@zpoken.io>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
penumbra-crypto = { path = "../crypto" }
penumbra-tct = { path = "../tct/" }
penumbra-transaction = { path = "../transaction", default-features = false }
penumbra-proto = { path = "../proto", default-features = false }
penumbra-chain = { path = "../chain", default-features = false }

anyhow = "1"
hex = "0.4"
base64 = "0.20.0-alpha.1"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2.83"}
serde-wasm-bindgen = "0.4.5"
js-sys = "0.3"
indexmap = "=1.9.2"
web-sys = { version = "0.3.4", features = ["console"] }
rand_core = { version = "0.6.3", features = ["getrandom"] }
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
