apiVersion: v1
kind: ConfigMap
metadata:
  name: "genesis"
data:
{{ $path := "pdcli/.penumbra/testnet_data/node0/tendermint/config/genesis.json" }}
{{- "genesis.json" | indent 2 }}{{ print ": "}}{{ $.Files.Get $path | b64enc -}}