scrape_configs:
  - job_name: 'Tendermint Node'
    scrape_interval: 10s
    scheme: http
    metrics_path: metrics
    static_configs:
      - targets: ['tendermint:26660']
  # NOTE: `pd` doesn't actually expose metrics yet, so this doesn't actually do
  # anything interesting...
  - job_name: 'Penumbra Daemon'
    scrape_interval: 10s
    scheme: http
    metrics_path: metrics
    static_configs:
      - targets: ['pd:9096']