[package]
name = "penumbra-component"
version = "0.63.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penumbra-storage = { path = "../../../storage", default-features = false }
async-trait = "0.1.52"
anyhow = "1"
tendermint = "0.34.0"
hex = "0.4"
