[package]
name = "penumbra-proto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
prost = "0.9"
tonic = "0.6"

[build-dependencies]
prost-build = "0.9"
tonic-build = "0.6"