[package]
name = "penumbra-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
prost = "0.9"
tonic = "0.6"
serde = { version = "1", features = ["derive"] }
hex = "0.4"
anyhow = "1.0"
subtle-encoding = "0.5"
bech32 = "0.8"
ibc-proto = { git = "https://github.com/penumbra-zone/ibc-rs" }

[build-dependencies]
prost-build = "0.9"
ibc-proto = { git = "https://github.com/penumbra-zone/ibc-rs" }
tonic-build = "0.6"
