[package]
name = "penumbra-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decaf377-fmd = { path ="../decaf377-fmd" }
decaf377-rdsa = { version = "0.5", git = "https://github.com/penumbra-zone/decaf377-rdsa" }
bytes = { version = "1", features = ["serde"] }
prost = "0.9"
tonic = "0.6"
serde = { version = "1", features = ["derive"] }
hex = "0.4"
anyhow = "1.0"
subtle-encoding = "0.5"
bech32 = "0.8"
ibc-proto = { git = "https://github.com/penumbra-zone/ibc-rs.git", branch = "with-tendermintrs-24" }
ibc = { git = "https://github.com/penumbra-zone/ibc-rs.git", branch = "with-tendermintrs-24" }
ics23 = { version = "0.7" }
prost-types = "0.9"
tendermint = "0.24.0-pre.1"
num-rational = "0.4"

[build-dependencies]
prost = "0.9"
prost-types = "0.9"
prost-build = "0.9"
ibc-proto = { git = "https://github.com/penumbra-zone/ibc-rs.git", branch = "with-tendermintrs-24" }
ics23 = { version = "0.7" }
tonic-build = "0.6"
