[package]
name = "penumbra-chain"
version = "0.65.0-alpha.1"
edition = "2021"

[dependencies]
# Workspace dependencies
cnidarium = { path = "../../../cnidarium", optional = true }
penumbra-proto = { path = "../../../proto", default-features = false }

# Penumbra dependencies
decaf377 = "0.5"

tendermint = "0.34.0"
ibc-types = { version = "0.11.0", default-features = false }
ics23 = "0.11.0"

# Crates.io deps
ark-ff = { version = "0.4", default_features = false }
anyhow = "1"
bytes = "1"
hex = "0.4"
once_cell = "1.8"
sha2 = "0.9"
serde = { version = "1", features = ["derive"] }
async-trait = "0.1.52"
tracing = "0.1"

# Component dependencies
tonic = { version = "0.10", optional = true }
tokio = { version = "1", optional = true }

[features]
component = [
    "cnidarium",
    "penumbra-proto/cnidarium",
    "penumbra-proto/rpc",
    "tonic",
    "tokio",
]
default = ["std", "component"]
std = ["ark-ff/std", "ibc-types/std"]
docsrs = []
