[package]
name = "penumbra-chain"
version = "0.52.0"
edition = "2021"

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../../../proto", default-features = false }
penumbra-storage = { path = "../../../storage", optional = true }
penumbra-tct = { path = "../../../crypto/tct" }
penumbra-crypto = { path = "../../crypto", default-features = false }
penumbra-component = { path = "../component", optional = true }

# Penumbra dependencies
decaf377 = "0.4"

tendermint = "0.31.1"
ibc-types = { git = "https://github.com/penumbra-zone/ibc-types", branch = "back-to-upstream-ibc-proto" }

ics23 = "0.9.0"

# Crates.io deps
ark-ff = { version = "0.4", default_features = false }
anyhow = "1"
bincode = "1.3.3"
bytes = "1"
hex = "0.4"
once_cell = "1.8"
sha2 = "0.9"
serde = { version = "1", features = ["derive"] }
async-trait = "0.1.52"
tracing = "0.1"

[features]
component = ["penumbra-component", "penumbra-storage", "penumbra-proto/penumbra-storage"]
default = ["std", "component"]
std = ["ark-ff/std"]
docsrs = []
