[package]
name = "pcli"
version = "0.1.0"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "The command-line interface for the Penumbra Zone"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../proto" }
penumbra-crypto = { path = "../crypto" , features = ["sqlx"]}
penumbra-wallet = { path = "../wallet" }

# Penumbra dependencies
ark-ff = { git = "https://github.com/penumbra-zone/algebra", branch = "ours" }
decaf377 = { git = "https://github.com/penumbra-zone/decaf377" }
tower-abci = { git = "https://github.com/penumbra-zone/tower-abci/" }
tendermint-proto = { git = "https://github.com/penumbra-zone/tendermint-rs.git", branch = "master" }
tendermint = { git = "https://github.com/penumbra-zone/tendermint-rs.git", branch = "master" }
# External dependencies
async-stream = "0.2"
bincode = "1.3.3"
blake2b_simd = "0.5"
bytes = "1"
comfy-table = "5"
directories = "4.0.1"
tokio = { version = "1", features = ["full"]}
tokio-stream = "0.1"
tokio-util = "0.6"
tower = { version = "0.4", features = ["full"]}
tracing = "0.1"
structopt = "0.3"
tonic = "0.6.1"
tracing-subscriber = "0.2"
pin-project = "1"
futures = "0.3"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1.11", features = ["hex"] }
reqwest = { version = "0.11", features = ["json"] }
sha2 = "0.9"
anyhow = "1"
hex = "0.4"
rand = "0.8"
rand_chacha = "0.3.1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres" ] }

[build-dependencies]
vergen = "5"
