{{- if .Values.ingressRoute.enabled -}}
{{ $count := (.Values.nodes | len | int) }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-https
  labels:
    {{- include "penumbra-node.labels" . | nindent 4 }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingressRoute.hosts.pd }}`)
    {{- with .Values.ingressRoute.middlewares }}
    middlewares:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    services:
{{- /*
Skip nodes with seed_mode=true when looping over nodes, to exclude from LB RPCs.
Otherwise, RPC can return surprising results, like very low numbers of peers.
*/}}
{{- range $i,$e := until $count }}
{{- $seed_mode := (index $.Values.nodes $i).seed_mode | default false }}
{{- if $seed_mode }}
{{- else }}
{{ $rpc_svc_name := printf "%s-fn-%d" $.Release.Name $i }}
    - name: {{ $rpc_svc_name }}
      port: 8080
      scheme: h2c
{{- end }}
{{- end }}
  - kind: Rule
    match: Host(`{{ .Values.ingressRoute.hosts.tm }}`)
    services:
{{- range $i,$e := until $count }}
{{- $seed_mode := (index $.Values.nodes $i).seed_mode | default false }}
{{- if $seed_mode }}
{{- else }}
{{ $rpc_svc_name := printf "%s-fn-%d" $.Release.Name $i }}
    - name: {{ $rpc_svc_name }}
      port: 26657
{{- end }}
{{- end }}
  tls:
    domains:
    - main: {{ .Values.ingressRoute.hosts.pd }}
      sans:
        - {{ .Values.ingressRoute.hosts.tm }}
    secretName: {{ .Values.ingressRoute.secretName }}
{{- end }}
