[package]
name = "penumbra-chain"
version = "0.52.0"
edition = "2021"

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../proto", default-features = false }
penumbra-storage = { path = "../storage", optional = true }
penumbra-component = { path = "../crates/component", optional = true }
penumbra-crypto = { path = "../crypto", default-features = false }
# penumbra-transaction = { path = "../transaction" }
penumbra-tct = { path = "../tct" }

# Penumbra dependencies
<<<<<<< HEAD
decaf377 = "0.4"
=======
decaf377 = "0.3.0"
<<<<<<< HEAD
>>>>>>> 7f272cc7 (# This is a combination of 2 commits.)
jmt = "0.4"

tendermint = "0.29.0"
ibc-types = { git = "https://github.com/penumbra-zone/ibc-types", branch = "0.1.x",  version = "0.1.1" }
=======
jmt = "0.5"

tendermint = "0.31.0"
ibc-types = { git = "https://github.com/penumbra-zone/ibc-types", branch = "0.2.x" }
>>>>>>> 0cf9ad68 (storage: tombstone deleted entries in the values cf)

ics23 = "0.10.0"

# Crates.io deps
ark-ff = { version = "0.4", default_features = false }
anyhow = "1"
bincode = "1.3.3"
bytes = "1"
hex = "0.4"
once_cell = "1.8"
sha2 = "0.9"
serde = { version = "1", features = ["derive"] }
async-trait = "0.1.52"
tracing = "0.1"

[features]
component = ["penumbra-component", "penumbra-storage", "penumbra-proto/penumbra-storage"]
default = ["std", "component"]
std = ["ark-ff/std"]
docsrs = []
