[package]
name = "penumbra-wasm"
version = "0.59.0"
authors = [
    "Valentine <valentine@zpoken.io>",
    "Gabe R. <gabe@penumbralabs.xyz"
]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
penumbra-asset         = { path = "../core/asset" }
penumbra-chain         = { path = "../core/component/chain", default-features = false }
penumbra-compact-block = { path = "../core/component/compact-block", default-features = false }
penumbra-dex           = { path = "../core/component/dex", default-features = false, features = ["proving-keys"] }
penumbra-fee           = { path = "../core/component/fee", default-features = false }
penumbra-keys          = { path = "../core/keys" }
penumbra-num           = { path = "../core/num" }
penumbra-proto         = { path = "../proto", default-features = false }
penumbra-sct           = { path = "../core/component/sct", default-features = false }
penumbra-shielded-pool = { path = "../core/component/shielded-pool", default-features = false, features = ["proving-keys"] }
penumbra-stake         = { path = "../core/component/stake", default-features = false }
penumbra-tct           = { path = "../crypto/tct" }
penumbra-transaction   = { path = "../core/transaction", default-features = false }

anyhow                   = "1.0.75"
base64                   = "0.21.2"
console_error_panic_hook = { version = "0.1.7", optional = true }
hex                      = "0.4.3"
indexed_db_futures       = "0.3.0"
rand_core                = { version = "0.6.4", features = ["getrandom"] }
serde                    = { version = "1.0.186", features = ["derive"] }
serde-wasm-bindgen       = "0.5.0"
wasm-bindgen             = "0.2.87"
wasm-bindgen-futures     = "0.4.37"
web-sys                  = { version = "0.3.64", features = ["console"] }
tracing = "0.1"
ark-ff = { version = "0.4", features = ["std"] }
decaf377 = { version = "0.5", features = ["r1cs"] }


[dev-dependencies]
wasm-bindgen-test = "0.3.37"
