[package]
name = "penumbra-wasm"
version = {workspace = true}
authors = {workspace = true}
edition = {workspace = true}

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]
mock-database = []

[dependencies]
penumbra-asset = {workspace = true, default-features = true}
penumbra-compact-block = {workspace = true, default-features = false}
penumbra-dex = {workspace = true, default-features = false}
penumbra-fee = {workspace = true, default-features = false}
penumbra-governance = {workspace = true, default-features = false}
penumbra-ibc = {workspace = true, default-features = false}
penumbra-keys = {workspace = true, default-features = true}
penumbra-num = {workspace = true, default-features = true}
penumbra-proof-params = {workspace = true, default-features = false}
penumbra-proto = {workspace = true, default-features = false}
penumbra-sct = {workspace = true, default-features = false}
penumbra-shielded-pool = {workspace = true, default-features = false}
penumbra-stake = {workspace = true, default-features = false}
penumbra-tct = {workspace = true, default-features = true}
penumbra-transaction = {workspace = true, default-features = false}
anyhow = {workspace = true}
ark-ff = {workspace = true, features = ["std"], default-features = true}
base64 = {workspace = true}
# penumbra-wasm = { git = "https://github.com/penumbra-zone/web.git", branch = "wasm-refactor", package = "penumbra-wasm", default-features = false }
penumbra-extension = {workspace = true, default-features = true}
console_error_panic_hook = { version = "0.1.7", optional = true }
decaf377 = {workspace = true, features = ["r1cs"], default-features = true}
hex = {workspace = true}
indexed_db_futures = "0.3.0"
rand_core = {workspace = true, features = ["getrandom"]}
serde = {workspace = true, features = ["derive"]}
serde-wasm-bindgen = "0.5.0"
thiserror = {workspace = true}
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = ["console"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
serde_json = {workspace = true}
