[package]
name = "penumbra-wasm"
version = "0.63.1"
authors = [
    "Valentine <valentine@zpoken.io>",
    "Gabe R. <gabe@penumbralabs.xyz"
]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
penumbra-asset         = { path = "../core/asset" }
penumbra-chain         = { path = "../core/component/chain", default-features = false }
penumbra-compact-block = { path = "../core/component/compact-block", default-features = false }
penumbra-dex           = { path = "../core/component/dex", default-features = false, features = ["proving-keys"] }
penumbra-fee           = { path = "../core/component/fee", default-features = false }
penumbra-ibc           = { path = "../core/component/ibc", default-features = false }
penumbra-keys          = { path = "../core/keys" }
penumbra-num           = { path = "../core/num" }
penumbra-proto         = { path = "../proto", default-features = false }
penumbra-sct           = { path = "../core/component/sct", default-features = false }
penumbra-shielded-pool = { path = "../core/component/shielded-pool", default-features = false, features = ["proving-keys"] }
penumbra-stake         = { path = "../core/component/stake", default-features = false }
penumbra-governance    = { path = "../core/component/governance", default-features = false, features = ["proving-keys"] }
penumbra-tct           = { path = "../crypto/tct" }
penumbra-transaction   = { path = "../core/transaction", default-features = false }

anyhow                   = "1.0.75"
ark-ff                   = { version = "0.4.2", features = ["std"] }
base64                   = "0.21.5"
console_error_panic_hook = { version = "0.1.7", optional = true }
decaf377                 = { version = "0.5", features = ["r1cs"] }
#gloo-utils               = { version = "0.2.0", features = ["serde"] }
hex                      = "0.4.3"
indexed_db_futures       = "0.3.0"
rand_core                = { version = "0.6.4", features = ["getrandom"] }
serde                    = { version = "1.0.192", features = ["derive"] }
serde_json = { version = "1" }
serde-wasm-bindgen       = "0.6.1"
thiserror                = "1.0.50"
wasm-bindgen             = "0.2.88"
wasm-bindgen-futures     = "0.4.38"
wasm-bindgen-test        = "0.3.38"
web-sys                  = { version = "0.3.65", features = ["console"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.38"
