[package]
name = "penumbra-shielded-pool"
version = "0.52.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
component = [
    "penumbra-component",
    "penumbra-storage",
    "penumbra-proto/penumbra-storage",
    "penumbra-chain/component",
    "penumbra-sct/component"
]
proving-keys = ["penumbra-proof-params/proving-keys"]
default = ["std", "component", "proving-keys"]
std = ["ark-ff/std"]
docsrs = []

[dependencies]
# Workspace dependencies
penumbra-crypto = { path = "../../crypto", default-features = false }
penumbra-proto = { path = "../../proto", default-features = false }
penumbra-sct = { path = "../sct", default-features = false }
# TODO: invert
penumbra-component = { path = "../component", optional = true }
penumbra-storage = { path = "../../storage", optional = true }
penumbra-chain = { path = "../../chain", default-features = false }
penumbra-tct = { path = "../../tct" }
penumbra-proof-params = { path = "../../proof-params", default-features = false }

# Penumbra dependencies
decaf377-rdsa = { version = "0.6" }

# Crates.io dependencies
ark-ff = { version = "0.4", default_features = false }
metrics = "0.19.0"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
anyhow = "1"
async-trait = "0.1.52"
tendermint = "0.29.0"
blake2b_simd = "0.5"
bytes = "1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
im = "15.1"


