---
# Deploys the most recent tagged testnet (e.g. "037-iocaste.2") to cluster
# at testnet.penumbra.zone.
name: Deploy testnet.penumbra.zone
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        # We cannot set a meaningful default here, because we always want the latest tag.
        # Inputs cannot reference special variables like `github.ref_name`, so we default
        # to the value of `github.ref_name` when exporting the env var in the deploy step.
        required: true
  push:
    tags:
      - '*-?v[0-9]+*'
jobs:
  # Before deploying, we must wait for the container build to complete,
  # so that the relevant tag is present in container registry.
  build-container:
    name: Build container for testnet
    uses: ./.github/workflows/containers.yml
    secrets: inherit
  deploy:
    name: Deploy testnet to cluster
    needs:
      - build-container
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: testnet
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - id: gcloudauth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/1006847873719/locations/global/workloadIdentityPools/gh-runner-pool/providers/my-provider'
          service_account: 'github-actions@penumbra-sl-testnet.iam.gserviceaccount.com'

      - name: get gke credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: testnet
          project_id: penumbra-sl-testnet
          location: us-central1

      - name: deploy
        run: |-
          cd deployments/
          export PENUMBRA_VERSION='${{ github.event.inputs.image_tag || github.ref_name }}'
          export HELM_RELEASE='penumbra-testnet'
          ./ci.sh

      - name: bounce grpcui
        run: kubectl rollout restart deployment grpcui-testnet
