---
# Deploys the latest changes on 'main' branch, via a container
# image tagged with 'main', to testnet-preview.penumbra.zone.
name: Deploy testnet-preview.penumbra.zone
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        # The container tag "main" comes from the name of the main branch.
        # It's important we deploy this tag for preview, rather than "latest",
        # as "latest" maps to the most recent tag (i.e. weekly testnet).
        default: "main"
        required: true
  push:
    branches:
      - main

# Cancel any pending preview deploys, in favor of a newer PR
# that was just merged.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-container:
    name: Build container for preview
    uses: ./.github/workflows/containers.yml
    secrets: inherit
  deploy:
    name: Deploy preview to cluster
    permissions:
      contents: 'read'
      id-token: 'write'
    needs:
      - build-container
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: testnet-preview
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - id: gcloudauth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/1006847873719/locations/global/workloadIdentityPools/gh-runner-pool/providers/my-provider'
          service_account: 'github-actions@penumbra-sl-testnet.iam.gserviceaccount.com'

      - name: get gke credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: testnet
          project_id: penumbra-sl-testnet
          location: us-central1

      - name: install helmfile
        run: |
          helmfile_version="0.157.0"
          helmfile_url="https://github.com/helmfile/helmfile/releases/download/v${helmfile_version}/helmfile_${helmfile_version}_linux_amd64.tar.gz"
          mkdir -p /tmp/helmfile-download
          cd /tmp/helmfile-download || exit 1
          curl -SfL -O "$helmfile_url"
          tar -xzf helmfile*.tar.gz
          mkdir -p "$HOME/bin"
          cp helmfile "$HOME/bin/"
          export PATH="$HOME/bin:$PATH"
          which helmfile

      - name: deploy
        run: |-
          cd deployments/
          export PENUMBRA_VERSION='main'
          export HELM_RELEASE='penumbra-testnet-preview'
          ./ci.sh

      - name: bounce grpcui
        run: kubectl rollout restart deployment grpcui-preview

      - name: bounce osiris
        run: kubectl rollout restart deployment osiris-preview

      # We only run one (1) relayer instance, and re-deploy it as part of the preview update.
      # The other end of the configured path is the long-running testnet.
      # We ignore errors on the bounce, because we may have removed the deployment out of band:
      # we're still working on reliable packet relaying between test chains.
      - name: bounce relayer
        run: |-
          ./deployments/scripts/bounce-relayer || true
