---
# Deploys the latest changes on 'main' branch, via a container
# image tagged with 'main', to testnet-preview.penumbra.zone.
name: Deploy testnet-preview.penumbra.zone
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        # The container tag "main" comes from the name of the main branch.
        # It's important we deploy this tag for preview, rather than "latest",
        # as "latest" maps to the most recent tag (i.e. weekly testnet).
        default: "main"
        required: true
  push:
    branches:
      - main

jobs:
  build-container:
    name: Build container for preview
    uses: ./.github/workflows/containers.yml
    secrets: inherit
  deploy:
    name: Deploy preview to cluster
    permissions:
      contents: 'read'
      id-token: 'write'
    needs:
      - build-container
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: testnet-preview
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - id: gcloudauth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/1006847873719/locations/global/workloadIdentityPools/gh-runner-pool/providers/my-provider'
          service_account: 'github-actions@penumbra-sl-testnet.iam.gserviceaccount.com'

      - name: get gke credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: testnet
          project_id: penumbra-sl-testnet
          location: us-central1

      - name: deploy
        run: |-
          cd deployments/
          export PENUMBRA_VERSION='main'
          export HELM_RELEASE='penumbra-testnet-preview'
          ./ci.sh

      # We only run one (1) relayer instance, and re-deploy it as part of the preview update.
      # The other end of the configured path is the long-running testnet.
      - name: deploy relayer
        run: |-
          ./deployments/scripts/bounce-relayer
